 

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-07-14 09:14:48
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Text;

namespace LAFAFGS.Domain.Model
{
	public class cn  
	{
		#region 构造方法

		public cn()
		{
		
		}

		#endregion

		#region 属性	

		/// <summary>
		/// 
		/// 必填项
		/// </summary>
		public Guid ID { get; set; }
		/// <summary>
		/// 代偿ID
		/// 必填项
		/// </summary>
		public Guid SRGID { get; set; }
		/// <summary>
		/// 损失日期
		/// 必填项
		/// </summary>
		public DateTime LoseDate { get; set; }
		/// <summary>
		/// 损失金额
		/// 必填项
		/// </summary>
		public string LoseAmount { get; set; }
		/// <summary>
		/// 
		/// 必填项
		/// </summary>
		public DateTime UPD { get; set; }
		/// <summary>
		/// 
		/// 必填项
		/// </summary>
		public int Status { get; set; }
		

		#endregion

	}

	}


