//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2016-07-14 09:16:50 by 懒惰的肥兔
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	

	public class Direction
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public Guid ID { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Name { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Value { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? UPD { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? Status { get; set; }
		 
      
    }
}


